In [12]:
import pytest
import jax
import jax.numpy as jnp
import numpy as np
from dmri.train.dataloader import StreamDataLoader
import time

def simulator(rng):
    # Simple simulator that returns a random array
    return jax.random.normal(rng, shape=(10,))

In [26]:
default_kwargs = {
    'batch_size': 32,
    'max_queue_size': 100,
    'num_producers': 2,
    'data_device': 'cpu',
    'simulation_device': 'cpu',
}

loader = StreamDataLoader(simulator_fn=simulator, **default_kwargs)
# time.sleep(1)
batches = []
for i, batch in enumerate(loader):
    if i >= 1000:  # Test 3 batches
        break
    assert batch.shape == (32, 10)
    batches.append(batch)

In [28]:
batches[0] - batches[500]

Array([[-2.17319846e+00,  2.39648747e+00, -3.16279531e-02,
        -2.93007731e+00, -1.25922728e+00, -1.20529842e+00,
        -4.28238630e-01, -2.31889427e-01, -6.90402329e-01,
        -1.14996418e-01],
       [ 1.12518811e+00,  2.18280411e+00,  6.56739593e-01,
        -7.54753888e-01, -2.39200759e+00,  1.52005744e+00,
         1.16711879e+00,  1.18465051e-02, -5.70836484e-01,
         1.67952791e-01],
       [-6.29777133e-01, -1.52142954e+00,  1.00498903e+00,
        -1.86304116e+00,  1.66645527e+00,  8.06875050e-01,
         3.68123710e-01, -2.05977535e+00, -1.05585217e+00,
         3.13426822e-01],
       [ 3.46348166e-01,  1.70549464e+00, -5.78656018e-01,
        -3.12760592e+00, -1.20200956e+00, -2.51741362e+00,
        -1.02550411e+00,  2.04691100e+00,  2.18958330e+00,
         2.01460004e+00],
       [ 1.70776367e-01, -9.13502991e-01,  1.01999640e-01,
         1.16953015e+00, -8.04277420e-01, -3.85551482e-01,
         9.60783958e-01, -1.01926637e+00,  1.00721717e+00,
        -4.

In [46]:
for i, batch in enumerate(data):
    if i > 10:
        break

    print(batch.shape)
    batches.append(batch)

(32, 10)
(32, 10)
(32, 10)
(32, 10)
(32, 10)
(32, 10)
(32, 10)
(32, 10)
(32, 10)
(32, 10)
(32, 10)


In [49]:
batches[0][0]

Array([ 0.9441039 ,  0.25652114, -1.560658  ,  0.4111101 ,  0.7323572 ,
        1.5107379 ,  1.0902532 , -1.0785625 ,  1.1400133 , -0.8246483 ],      dtype=float32)

In [50]:
 batches[1][0]

Array([-0.4562426 , -0.10252944,  1.8902566 , -1.879439  ,  0.44196153,
       -0.64382577, -0.14653905, -0.3042834 ,  0.32795638, -0.15830906],      dtype=float32)